### ISSUE TITLE
New member tranminhtrong-vn

### ISSUE THREAD

**Issue by trongtranminh** [team-vietnam/members#15]
Hãy thực hiện những thao tác sau (từ [New member checklist](https://github.com/team-vietnam/members/wiki/New-member-checklist)). Thực hiện xong việc nào hãy đánh dấu check vào việc đó. Việc nào bạn đã nắm vững có thể bỏ qua. Trong quá trình xúc tiến hãy comment vào issue này để yêu cầu giúp đỡ.
- [x] Tạo [GitHub](https://github.com) account
- [x] Xem [video](https://youtu.be/5ue3qWR0mjA) hướng dẫn minh hoạ
- [x] Tạo [LinkedIn](https://www.linkedin.com) profile
- [x] Đọc [Hướng dẫn Git dành cho người mới bắt đầu](http://backlogtool.com/git-guide/vn/) và/hoặc [Learn Enough Git to Be Dangerous](https://www.learnenough.com/git-tutorial)
- [x] Fork repository [team-vietnam/members](https://github.com/team-vietnam/members) về GitHub repository cá nhân
- [x] Edit file [README.md](https://github.com/team-vietnam/members/blob/master/README.md) trên repository cá nhân đã fork
- [x] Tạo [Pull Request](https://help.github.com/articles/creating-a-pull-request/) trên repository cá nhân
- [x] Tập merge thông thường
- [x] Tập [Rebase](http://backlogtool.com/git-guide/vn/stepup/stepup2_8.html)
- [x] Tập [Squash](http://backlogtool.com/git-guide/vn/stepup/stepup6_6.html)
- [x] Sử dụng [GitHub pages](https://pages.github.com) để giới thiệu bản thân
- [x] Ghi tóm tắt mức độ quen thuộc của bạn đối với Git và [GitHub](https://github.com), vài lệnh Git mà bạn học được từ [Learn Enough Git to Be Dangerous](https://www.learnenough.com/git-tutorial)
- [x] Đọc [Learn Enough Command Line to Be Dangerous](https://www.learnenough.com/command-line-tutorial). Tóm tắt một số dòng lệnh Linux mà bạn tâm đắc nhất.
- [x] Tạo [Pull Request](https://help.github.com/articles/creating-a-pull-request/) yêu cầu merge từ repository cá nhân về repository [team-vietnam/members](https://github.com/team-vietnam/members). Trong Pull Request cần có description với đủ các nội dung yêu cầu trong checklist này. Tham khảo [PR6](https://github.com/team-vietnam/members/pull/6)

**Comment by trongtranminh** [comment]
GitHub pages url: https://tranminhtrong.github.io/

**Comment by vochicong** [comment]
GitHub page pro phết 👍 

Gắn link PR trước của Trọng: https://github.com/team-vietnam/members/pull/11
