### ISSUE TITLE
Add member khuongnh to member list

### ISSUE THREAD

**Issue by vochicong** [team-vietnam/members#5]
Add khuongnh to [member list](https://github.com/team-vietnam/members/blob/master/README.md)

@khiemht-vn cho anh biết chính xác GitHub account của Khương để anh add vào GitHub team. Sau đấy chúng ta nhờ Khương tự cập nhật member list để add bản thân vào.

**Comment by khiemht-vn** [comment]
Dạ anh @vochicong . Để em request Khương nhé.

**Comment by vochicong** [comment]
@khiemht-vn hướng dẫn @nguyenhuukhuong1986 làm theo hướng dẫn tại https://github.com/team-vietnam/members/wiki để tự add bản thân vào member list nhé!
